
#                _                 _      _____      _                _             __   __
#       /\      | |               | |    / ____|    | |              | |            \ \ / /
#      /  \   __| |_   _____ _ __ | |_  | |     __ _| | ___ _ __   __| | __ _ _ __   \ V /
#     / /\ \ / _` \ \ / / _ \ '_ \| __| | |    / _` | |/ _ \ '_ \ / _` |/ _` | '__|   > <
#    / ____ \ (_| |\ V /  __/ | | | |_  | |___| (_| | |  __/ | | | (_| | (_| | |     / . \
#   /_/    \_\__,_| \_/ \___|_| |_|\__|  \_____\__,_|_|\___|_| |_|\__,_|\__,_|_|    /_/ \_\

# !!! FOR TEXT FORMATTING, PLEASE REFER TO THIS GUIDE:
# https://docs.advntr.dev/minimessage/format.html
# !!!

#A list of worlds, where the plugin should take effect
worlds:
  - "world"
  - "world_nether"
  - "world_the_end"


# The name, that shows in the top of the calendar gui
inventoryname: "<dark_gray>Advent Calendar"

# Select the present material
# You can choose between "numbered", "red", "blue", "green", "purple", "yellow" or "white"
presentType: "red"

# The material, to fill the background with
# User AIR if you want no background
fillMaterial: "GRAY_STAINED_GLASS_PANE"

# The name format of the presents
# Use %num% for the day number
presentName: "<red>December %num%"
# The lore of the present
# Use %num% for the day number
presentLore:
  - "<gray>Click to claim your present"

# The name of the close button
closeBtnName: "<red>Close"
# The material of the close button
closeBtnMaterial: "BARRIER"

days:
  1:
    # Override the default name
    name: "<red><b>December 1"
    # Override the default lore
    lore:
      - "<gray>Click to claim your present"
    # Override the default head
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzFmMjNjZTkzNmQzMmM3Y2QyYmIxY2JkOThhMDM0NThmZmZkNTMwZWRhYTM3M2I4ODJjYzRlZjY2NDM1M2ZkNCJ9fX0="
    # Specify commands, that get executed when a player opens the present
    # Only commands, that work in the console, can be pasted here
    # DON'T put a "/" in front of the commands
    commands:
      - say day 1
      - give %player% minecraft:diamond 1
  2:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  3:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  4:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  5:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  6:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  7:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  8:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  9:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  10:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  11:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  12:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  13:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  14:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  15:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  16:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  17:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  18:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  19:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  20:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  21:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  22:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  23:
    #name: "customname"
    #lore:
    #  - "<gray>Click to claim your present"
    #  - "<reset>"
    commands:
      - say You opened a present
      - give %player% minecraft:diamond 1
  24:
    #name: "customname"
    lore:
      - "<gray>Click to claim your present"
      - "<red><b>Merry Christmas!"
    commands:
      - say Merry Christmas!
      - give %player% minecraft:diamond 1

# Modify all plugin messages
messages:
  prefix: "<dark_gray>[<red>AdventCalendarX<dark_gray>]"
  usageError: "<red>Usage: %usage%"
  noPermissionError: "<red>You don't have permission to use this!"
  versionMessage: "<gray>You are using version %version%"

skulls:
  red: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDUzNjhmNTYzNWZmNmMzNDA3ZjBmMzU2YzViNmUwOTQ3YmNkNWUzODQ5MGM5YWE4YjhiNTgyYTRmMjFhZTNjYiJ9fX0="
  blue: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWI4NWUyOWYyOWVjOWE5MGU0ODJlYTViODM5MWJjYjQ1NjBiYmFlMGRjZDE1ZDdjZTFkODYwMTZiNDM1NmU5OCJ9fX0="
  green: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjhkYzNjODQ0OTFjNGZmMTAzZGU2ZWEwMTg4MGUyZDgzNDMyY2Q0ODc4Yjg0ZDZiNDMyNTNjYzUxZmQ5NzhlNyJ9fX0="
  white: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTQ3YjM3ZTY3YTg5MTU5YmY0YWNjNGE0NGQ0MzI4ZjRlZmMwMTgxNjA1MTQyMjg4ZTVlZWQxYWI4YWVkOTEzYyJ9fX0="
  purple: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTllMzlkOTFjMDRjMzBjYzFmNTMwZmVlNzk4ZWVkMjc5ZGRlNjBmOTVjMmUxZDE1NWMwZmRkMzYxZDA5NjJlZCJ9fX0="
  yellow: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWJkOTg3OTJkZDkyZDk3MTk4OTQzNDFhYzkwMTJhNTg0YzQ0Mjg1NThmZDJjNzEyZjc4ZTVmMGQ0ZGE4NTQ3MCJ9fX0="